version: "3.3"
name: "electric_quickstart"

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    restart: always

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
